# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: prometheus-libvirt-exporter
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: prometheus-libvirt-exporter
    dir: .
    main: ./main.go
    binary: prometheus-libvirt-exporter
    env:
      - CGO_ENABLED=0 # build a static binary without C dependencies
    flags:
      - -tags=netgo
      - -v
      - -a
    ldflags:
      - -w -s
      - -X main.version={{ .Version }} -X main.commit={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64

#Configuration for building packages for apk, deb and rpm package managers
nfpms:
  - id: "prometheus-libvirt-exporter"
    package_name: "prometheus-libvirt-exporter"
    file_name_template: prometheus-libvirt-exporter-{{ .Version }}.{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
    ids:
      - prometheus-libvirt-exporter
    maintainer: "vmindtech"
    description: |
      Prometheus-libvirt-exporter service (host and vm metrics exposed for prometheus, written in Go with pluggable metric collectors)
    homepage: "https://github.com/vmindtech/prometheus-libvirt-exporter"
    license: "MIT License"
    formats:
      - deb
      - rpm
    bindir: "/usr/bin"
    priority: optional
    contents:
      - src: contrib/prometheus-libvirt-exporter.service
        dst: /etc/systemd/system/prometheus-libvirt-exporter.service

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    formats: [ tar.gz ]
    wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}_checksums.txt"
  algorithm: sha256

# Configuration for GitHub Releases
release:
  github:
    owner: vmindtech
    name: prometheus-libvirt-exporter
  prerelease: auto
  replace_existing_draft: true
